Kigl/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ControlPanel.Common.Enums;
using ControlPanel.Domain.Contracts;
using Kigl.Domain.Contracts;
using Kigl.Filters;
using Kigl.Models;

namespace Kigl.Controllers
{
    [KiglAuthorize(RoleName.Admin)]
    public class CompanyController : BaseController
    {
        private readonly IAdvertiserService _advertiserService;

        public CompanyController(IUserService userService, IAdvertiserService advertiserService) : base(userService)
        {
            _advertiserService = advertiserService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var model = new ListAdvertiserModel
            {
                Advertisers = _advertiserService.GetAdvertisersOrderedByTime()
            };
            return View(model);
        }

        [HttpGet]
        public ActionResult ValidateCompanyName(string name)
        {
            var result = _advertiserService.ValidateAdvertiser(name);
            return SuccessCamelCaseResult(result);
        }

        [HttpGet]
        public ActionResult ValidateEditedCompanyName(string name, string advertiserId)
        {
            var result = _advertiserService.ValidateEditedAdvertiser(name, advertiserId);
            return SuccessCamelCaseResult(result);
        }

        [HttpPost]
        public ActionResult Edit(EditAdvertiserModel model, string submit)
        {
            if(String.IsNullOrEmpty(submit) || submit == Resources.Global.Admin_Edit)
                _advertiserService.AddOrUpdateAdvertiser(model);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Remove(String advertiserId)
        {
            Guid id;
            if(Guid.TryParse(advertiserId, out id))
            {
                _advertiserService.Remove(id);
            }

            return null;
        }

        [HttpPost]
        public ActionResult UpdateApprovedStatus(String advertiserId, Boolean isApproved)
        {
            Guid id;
            if (Guid.TryParse(advertiserId, out id))
            {
                _advertiserService.UpdateApprovedStatus(id, isApproved);

                if (isApproved)
                {
                    _advertiserService.UpdateRejectedStatus(id, false);
                }
            }

            return null;
        }

        [HttpPost]
        public ActionResult UpdateRejectedStatus(String advertiserId, Boolean isRejected)
        {
            Guid id;
            if (Guid.TryParse(advertiserId, out id))
            {
                _advertiserService.UpdateRejectedStatus(id, isRejected);

                if (isRejected)
                {
                    _advertiserService.UpdateApprovedStatus(id, false);
                }
            }

            return null;
        }
    }
}

Kigl/Views/Company/Index.cshtml
@using Global = Resources.Global;
@model Kigl.Models.ListAdvertiserModel
@{
    ViewBag.Title = "Companies";
    Int32 checkboxNum = 1;
}

<!-- begin users -->
<div class="rates">
    <div class="advertisers__header">
        <span class="rates_title">@Global.Admin_Advertisers</span>
        <a href="#" class="profileInfo__btn modal__link" data-modal="js__modal-1">@Global.Admin_AddAdvertiser</a>
    </div>
    <!-- begin users__table -->
    <div class="users__table_wrap adaptive_table">
        <div class="users__table">
            
            @foreach (var advertiser in Model.Advertisers)
            {
                <div class="users__row"  data-advertiser-id="@advertiser.Id">
                    <div class="users__col users__col1">
                        <div class="users__head users__head1">@Global.Admin_Advertiser</div>
                        <div class="users__box user_name users__box1">@advertiser.Name</div>
                    </div>
                    <div class="users__col users__col2">
                        <div class="users__head users__head2">@Global.Admin_Advertiser_Email</div>
                        <div class="users__box users__box2">@advertiser.Email</div>
                    </div>

                    <div class="users__col users__col3">
                        <div class="users__head users__head3">@Global.Admin_Company_BrandName</div>
                        <div class="users__box users__box3">@advertiser.BrandName</div>
                    </div>
                    <div class="users__col users__col4">
                        <div class="users__head users__head4">@Global.Admin_Company_ContactPerson</div>
                        <div class="users__box users__box4">@advertiser.ContactPerson</div>
                    </div>
                    <div class="users__col users__col5">
                        <div class="users__head users__head5">@Global.Admin_Company_AccountLink</div>
                        <div class="users__box users__box5">@advertiser.AccountLink</div>
                    </div>
                    <div class="users__col users__col6">
                        <div class="users__head users__head6"></div>
                        <div class="users__box users__box6">
                            <input type="checkbox" name="check_rates" id="checkbox-@checkboxNum" class="users__box6__check" @(advertiser.IsApproved?"checked":"")/>
                            <label for="checkbox-@checkboxNum"></label>
                            <button class="edit"><img src="../img/edit__blue.png" alt=""></button>
                            <button class="delete" style="@(advertiser.IsRejected?"display:none":"")"><img src="../img/delete.png" alt=""></button>
                        </div>
                    </div>
                </div><!-- /.users__row -->
                checkboxNum++;
            }
        </div>
    </div>
    <!-- end users__table -->
</div>
<!-- end users -->

@section Modals{
    <!-- begin modal -->
    <div class="modal fade" id="js__modal-1">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                    <h4 class="modal-title"><span>@Global.Admin_AddAdvertiser</span></h4>
                </div>
                <div class="modal-body">
                    <!-- begin rates__form -->
                    @using (Html.BeginForm("Edit", "Company", FormMethod.Post, new { id = "frmCreateUser", @class = "rates__form modal__form" }))
                    {
                        <div class="rates__item">
                            <input type="text" name="Name" class="input_name" placeholder="Advertiser">
                        </div>
                        <div class="rates__item">
                            <input type="email" name="Email" class="input_email" placeholder="Email">
                        </div>
                        <div class="rates__item">
                            <input type="text" name="BrandName" class="input_name" placeholder="Brand Name" onclick="this.placeholder=''">
                        </div>
                        <div class="rates__item">
                            <input type="text" name="ContactPerson" class="input_name" placeholder="Contact Person" onclick="this.placeholder=''">
                        </div>
                        <div class="rates__item">
                            <input type="text" name="AccountLink" class="input_web" placeholder="Website Link" onclick="this.placeholder=''">
                        </div>
                        <div class="rates__submit">
                            <div class="rates__submit-input">
                                <input type="submit" value="@Global.Admin_Create">
                            </div>
                        </div>
                    }
                    <!-- end rates__form -->
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- end modal -->
    <!-- begin modal -->
    <div class="modal fade" id="js__modal-2">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                    <h4 class="modal-title"><span>@Global.Admin_EditAdvertiser</span></h4>
                </div>
                <div class="modal-body">
                    <!-- begin rates__form -->
                    @using (Html.BeginForm("Edit", "Company", FormMethod.Post, new { id = "frmEditUser", @class = "rates__form modal__form" }))
                    {
                        <div class="rates__item">
                            <input id="user_edit_name" type="text" name="Name" class="input_name">
                        </div>
                        <input id="advertiser_id" type="hidden" name="Id" value="" />
                        <div class="rates__item">
                            <input id="user_edit_email" type="email" name="Email" class="input_email">
                        </div>
                        <div class="rates__item">
                            <input id="user_edit_brandName" type="text" name="BrandName" class="input_name" placeholder="Brand Name" onclick="this.placeholder=''">
                        </div>
                        <div class="rates__item">
                            <input id="user_edit_contactPerson" type="text" name="ContactPerson" class="input_name" placeholder="Contact Person" onclick="this.placeholder=''">
                        </div>
                        <div class="rates__item">
                            <input id="user_edit_accountLink" type="text" name="AccountLink" class="input_web" placeholder="Website Link" onclick="this.placeholder=''">
                        </div>
                        <div class="rates__submit">
                            <div class="rates__submit-input">
                                @*<input id="deleteBtn" type="submit" value="@Global.Admin_DeleteUser" name="submit">*@
                                <input type="submit" value="@Global.Admin_Edit" name="submit">
                            </div>
                        </div>
                    }
                    <!-- end rates__form -->
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- end modal -->

    <!-- begin modal -->
    <div class="modal fade" id="js__modal-3">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                    <h4 class="modal-title"><span>@Global.Instagram_AreYouSureToDelete</span></h4>
                    <input id="adIdToDelete" type="hidden" value="">
                </div>
                <div class="modal-body">
                    <div class="modal__text-med"></div>
                    <div class="modal__buttons-block">
                        <a href="#" class="modal__buttons-cancel">@Global.Instagram_AreYouSureToDelete_No</a>
                        <a href="#" class="profileInfo__btn2 btn-delete">@Global.Instagram_AreYouSureToDelete_Yes</a>
                    </div>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- end modal -->
}

@section Scripts{
    <script type="text/javascript">
        $(function() {
            $('.users__box6__check').click(function () {
                var isApproved = $(this).is(":checked");

                var row = $(this).closest('.users__row');
                var advertiserId = row.data('advertiser-id');

                var deleteBtn = $(this).siblings('.delete');

                $.post('@Url.Action("UpdateApprovedStatus")', {
                    advertiserId: advertiserId,
                    isApproved: isApproved
                }, function (data) {
                    if (isApproved) {
                        deleteBtn.show();
                    }
                });
            });

            $('.delete').click(function () {
                var row = $(this).closest('.users__row');
                var advertiserId = row.data('advertiser-id');

                var deleteBtn = $(this);
                var approvedChk = $(this).siblings('.users__box6__check');

                $.post('@Url.Action("UpdateRejectedStatus")', {
                    advertiserId: advertiserId,
                    isRejected: true
                }, function (data) {
                    deleteBtn.hide();
                    approvedChk.prop("checked", false);
                });
            });

            $('#frmCreateUser')
					.validate({
						rules: {
						    Name: {
						        required: true,
						        remote: '@Url.Action("ValidateCompanyName", "Company")'
						    },
						    Email: 'required',
						},
						messages: {
						    Name: '',
						    Email: '',
						}
					});

            $('#frmEditUser')
					.validate({
					    rules: {
					        Name: {
					            required: true,
					            remote: {
					                url: '@Url.Action("ValidateEditedCompanyName", "Company")',
					                type: 'get',
					                data: {
					                    advertiserid: function () {
					                        return $('#advertiser_id').val();
					                    }
					                },
					            },
					        },
					        Email: 'required',
					    },
					    messages: {
					        Name: '',
					        Email: '',

					    }
					});

            $('#js__modal-1').click(function () {
            });

            $(".edit").click(function (event) {
                var adv_name = $(this).closest(".users__row").find('.users__box1').text();
                var adv_email = $(this).closest(".users__row").find('.users__box2').text();
                var adv_brandName = $(this).closest(".users__row").find('.users__box3').text();
                var adv_contactPerson = $(this).closest(".users__row").find('.users__box4').text();
                var adv_accountLink = $(this).closest(".users__row").find('.users__box5').text();
                var row = $(this).closest('.users__row');
                var advertiserId = row.data('advertiser-id');

                $('#user_edit_name').val(adv_name);
                $('#user_edit_email').val(adv_email);
                $('#user_edit_brandName').val(adv_brandName);
                $('#user_edit_contactPerson').val(adv_contactPerson);
                $('#user_edit_accountLink').val(adv_accountLink);
                $('#advertiser_id').val(advertiserId);

                $('#js__modal-2').modal('show');

                setTimeout(function () {
                    $("#user_edit_name").focus();
                }, 500);
            });

            $('.modal__buttons-cancel').click(function () {
                $('#js__modal-3').modal('hide');
            });
        });
    </script>
}