Kigl/Controllers/BankAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ControlPanel.Common.Enums;
using ControlPanel.Domain.Contracts;
using Kigl.Domain.Contracts;
using Kigl.Filters;
using Kigl.Models;

namespace Kigl.Controllers
{
    [KiglAuthorize(RoleName.Admin)]
    public class BankAccountsController : BaseController
    {
        private readonly IAccountsService _accountService;
        private readonly IAdvertiserService _advertiserService;
        private readonly ISettingsService _settingsService;

        public BankAccountsController(IUserService userService, IAccountsService accountService, IAdvertiserService advertiserService, ISettingsService settingsService) : base(userService)
        {
            _accountService = accountService;
            _advertiserService = advertiserService;
            _settingsService = settingsService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var model = new ListAccountModel
            {
                Accounts = _accountService.GetAccounts(),
                Advertisers = _advertiserService.GetAdvertisers(true),
                Currencies = _settingsService.GetCurrencies()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EditAccountModel model)
        {
            _accountService.AddOrUpdateAccount(model);
            return RedirectToAction("Index");
        }
    }
}

Kigl/Views/BankAccounts/Index.cshtml
@model Kigl.Models.ListAccountModel
@using Global = Resources.Global;
@{
    ViewBag.Title = "Accounts";
}

<!-- begin accounts -->
<div class="accounts">
    <div class="advertisers__header">
        <span>@Global.Admin_Accounts</span>
        <a href="#" class="profileInfo__btn btn-add-account" >@Global.Admin_Add @Global.Admin_Account</a>
    </div>
    <div class="accounts__table">
        <div class="accounts__row">
            <div class="accounts__head accounts__head1">@Global.Admin_Number</div>
            <div class="accounts__head accounts__head2">@Global.Admin_Balance</div>
            <div class="accounts__head accounts__head3">@Global.Admin_Advertiser</div>
            <div class="accounts__head accounts__head4">@Global.Admin_Currency</div>
        </div>
        @foreach (var account in Model.Accounts)
        {
            <div class="accounts__row" data-account-id="@account.Id" data-balance="@account.Balance" data-advertiser-id="@(account.Advertiser?.Id)" data-currency-id="@(account.Currency?.Id)">
                <div class="accounts__box accounts__box1 account-number">@account.Number</div>
                <div class="accounts__box accounts__box2">$@account.Balance</div>
                <div class="accounts__box accounts__box3">@(account.Advertiser?.Name)</div>
                <div class="accounts__box accounts__box4">@(account.Currency?.Name)</div>
                <div class="accounts__box accounts__box5">
                    <a href="#" class="accounts__edit link__edit">
                        <svg xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" fill="#000000" version="1.1" x="0px" y="0px" viewBox="0 0 100 100"><g transform="translate(0,-952.36218)"><path d="m 79.652601,958.34659 a 3.0003,3.0003 0 0 0 -0.3124,0.0312 3.0003,3.0003 0 0 0 -1.7813,0.875 l -45.25,45.25001 a 3.0003,3.0003 0 0 0 -0.875,1.7812 l -1.4063,12.7188 a 3.0003,3.0003 0 0 0 3.3126,3.3125 l 12.7187,-1.4063 a 3.0003,3.0003 0 0 0 1.8125,-0.8437 l 45.25,-45.25001 a 3.0003,3.0003 0 0 0 0,-4.25 l -11.3125,-11.3125 a 3.0003,3.0003 0 0 0 -2.1563,-0.90625 z m 0.031,7.25 7.0625,7.09375 -1.4062,1.40625 -7.0626,-7.0625 1.4063,-1.4375 z m -70.9999998,2.78125 a 3.0003,3.0003 0 0 0 -2.6872,3 l 0,71.99996 a 3.0003,3.0003 0 0 0 3,3 l 71.9999998,0 a 3.0003,3.0003 0 0 0 3,-3 l 0,-48.99996 a 3.0003,3.0003 0 1 0 -6,0 l 0,45.99996 -66,0 0,-65.99996 46,0 a 3.0003,3.0003 0 1 0 0,-6 l -48.9999998,0 a 3.0003,3.0003 0 0 0 -0.3125,0 z m 65.3436998,2.875 7.0626,7.09375 -34.6563,34.65621 -7.0625,-7.0937 34.6562,-34.65626 z m -37.1874,40.59376 3.6562,3.6562 -4.0938,0.4688 0.4376,-4.125 z" fill-opacity="1" stroke="none" marker="none" visibility="visible" display="inline" overflow="visible" /></g></svg>
                    </a>

                    @*<a href="#" class="accounts__cancel link__cancel">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="#000000" data-name="Layer 1" viewBox="0 0 100 100" x="0px" y="0px"><title>icons</title><g data-name="13. circle across"><path d="M88.47,50C88.19,66.07,78.32,80.78,63,86.23a38.48,38.48,0,0,1-46-56A38.85,38.85,0,0,1,57.82,12.32C75.7,16,88.16,32,88.47,50c0,1.93,3,1.93,3,0A42,42,0,0,0,64.41,11.11a41.48,41.48,0,0,0-50,60.19A41.89,41.89,0,0,0,57.29,90.83c19.79-3.48,33.84-21,34.19-40.83C91.5,48.07,88.5,48.07,88.47,50Z" /><path d="M20.27,25.73L77.2,79.32c1.41,1.32,3.53-.79,2.12-2.12L22.39,23.61c-1.41-1.32-3.53.79-2.12,2.12h0Z" /></g></svg>
                    </a>
                    <a href="#" class="accounts__close link__close">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="0 0 25 25" x="0px" y="0px"><path d="M17.449 6.843l-4.949 4.95-4.95-4.95-0.707 0.707 4.95 4.95-4.95 4.949 0.707 0.708 4.95-4.95 4.949 4.95 0.707-0.708-4.949-4.949 4.949-4.95z" /><path d="M12.5 0c-6.904 0-12.5 5.596-12.5 12.5 0 6.903 5.596 12.5 12.5 12.5s12.5-5.597 12.5-12.5c0-6.904-5.596-12.5-12.5-12.5zM12.5 24c-6.328 0-11.5-5.172-11.5-11.5 0-6.329 5.172-11.5 11.5-11.5s11.5 5.171 11.5 11.5c0 6.328-5.172 11.5-11.5 11.5z" /></svg>
                    </a>*@
                </div>
            </div>
        }
    </div>
</div>
<!-- end accounts -->

@section Modals{
    <!-- begin modal -->
    <div class="modal fade" id="js__modal-2">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                    <h4 class="modal-title"><span class="operation">@Global.Admin_Add</span><span> @Global.Admin_Account</span></h4>
                </div>
                <div class="modal-body">
                    <!-- begin rates__form -->
                    @using (Html.BeginForm("Edit", "BankAccounts", FormMethod.Post, new { id = "frmEditAccount", @class = "rates__form modal__form" }))
                    {
                        <input type="hidden" name="Id" id="accountId"/>
                        <div class="rates__item">
                            <label>@Global.Admin_Number</label>
                            <input type="text" id="number" name="Number">
                        </div>
                        <div class="rates__item">
                            <label for="">@Global.Admin_Balance</label>
                            <input type="text" id="balance" name="Balance">
                        </div>
                        <div class="rates__item">
                            <label for="">@Global.Admin_Currency</label>
                            <div class="rates__select">
                                <select class="js-select" id="currencyId" name="CurrencyId">
                                    @foreach (var currency in Model.Currencies)
                                    {
                                        <option value="@currency.Id">@currency.Name</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="rates__item">
                            <label for="">@Global.Admin_Advertiser</label>
                            <div class="rates__select">
                                <select class="js-select" id="advertiserId" name="AdvertiserId">
                                    @foreach (var advertiser in Model.Advertisers)
                                    {
                                        <option value="@advertiser.Id">@advertiser.Name</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="rates__submit">
                            <div class="rates__submit-input">
                                <input type="submit" value="create">
                            </div>
                        </div>

                    }
                    <!-- end rates__form -->
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
    <!-- end modal -->
}

@section Scripts{
    <script type="text/javascript">
        $(function() {
            $('#frmEditAccount')
                .validate({
                    rules: {
                        Number: {
                            required: true,
                            digits: true
                        },
                        Balance: {
                            required: true,
                            number: true
                        },
                        CurrencyId: 'required',
                        AdvertiserId: 'required'
                    },
                    messages: {
                        Number: '',
                        Balance: '',
                        CurrencyId: '',
                        AdvertiserId: ''
                    }
                });

            $('.btn-add-account').click(function () {
                $('#accountId').val('');
                $('#number').val('');
                $('#balance').val('');
                $('#currencyId').val('');
                $('#currencyId').trigger('update.fs');
                $('#advertiserId').val('');
                $('#advertiserId').trigger('update.fs');
                $('.operation').text('@Global.Admin_Add');
                $('.rates__submit-input input').val('@Global.Admin_Create');
                $('#js__modal-2').modal('show');
            });

            $('.accounts__edit').click(function () {
                var row = $(this).closest('.accounts__row');
                $('#accountId').val(row.data('accountId'));
                $('#number').val(row.find('.account-number').text());
                $('#balance').val(row.data('balance'));
                
                $('#currencyId').val(row.data('currencyId'));
                $('#currencyId').trigger('update.fs');
                $('#advertiserId').val(row.data('advertiserId'));
                $('#advertiserId').trigger('update.fs');
                $('.operation').text('@Global.Admin_Add');
                $('.rates__submit-input input').val('@Global.Admin_Update');
                $('#js__modal-2').modal('show');
            });
        });
    </script>
}