Kigl/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ControlPanel.Common.Enums;
using ControlPanel.Domain.Contracts;
using Kigl.Domain.Contracts;
using Kigl.Filters;
using Kigl.Models;

namespace Kigl.Controllers
{
    [KiglAuthorize(RoleName.Admin)]
    public class SettingsController : BaseController
    {
        private readonly ISettingsService _settingsService;

        public SettingsController(IUserService userService, ISettingsService settingsService) : base(userService)
        {            
            _settingsService = settingsService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var model = new SettingsModel
            {
                Countries = _settingsService.GetCountries(),
                Cities = _settingsService.GetCities(),
                Currencies = _settingsService.GetCurrencies(),
                Networks = _settingsService.GetNetworks()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult AddCountry(string countryName)
        {
            var country = _settingsService.AddCountry(countryName);
            return SuccessResult(country);
        }

        [HttpPost]
        public ActionResult AddCurrency(string currencyName)
        {
            var currency = _settingsService.AddCurrency(currencyName);
            return SuccessResult(currency);
        }

        [HttpGet]
        public ActionResult EditCity()
        {
            var model = new EditCityModel
            {
                Countries = _settingsService.GetCountries()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult EditCity(EditCityModel model)
        {
            _settingsService.AddCity(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditNetwork()
        {
            var model = new EditNetworkModel
            {
                Cities = _settingsService.GetCities()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult EditNetwork(EditNetworkModel model)
        {
            _settingsService.AddNetwork(model);
            return RedirectToAction("Index");
        }
    }
}

Kigl/Views/Settings/EditCity.cshtml
@model Kigl.Models.EditCityModel
@{
    ViewBag.Title = "Edit city";
}

<h2>Edit city</h2>

@using (Html.BeginForm("EditCity", "Settings", FormMethod.Post, new { id = "frmEditCity", @class = "form-horizontal" }))
{
    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        <label for="Name" class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label for="countryId" class="col-sm-2 control-label">Country</label>
        <div class="col-sm-10">
            <select id="countryId" name="CountryId" class="form-control">
                <option value="">Select country</option>
                @foreach (var country in Model.Countries)
                {
                    if (country.Id == Model.CountryId)
                    {
                        <option value="@country.Id" selected="selected">@country.Name</option>
                    }
                    else
                    {
                        <option value="@country.Id">@country.Name</option>
                    }
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Create</button>
        </div>
    </div>
}

@section Scripts{
    <script type="text/javascript">
        $(function () {
            $('#frmEditCity')
                .validate({
                    rules: {
                        Name: 'required',
                        CountryId: 'required'
                    },
                    messages: {
                        Name: 'Please specify city name',
                        CountryId: 'Please select country'
                    }
                });
        });
    </script>
}

Kigl/Views/Settings/EditNetwork.cshtml
@model Kigl.Models.EditNetworkModel
@{
    ViewBag.Title = "Edit network";
}

<h2>Edit network</h2>

@using (Html.BeginForm("EditNetwork", "Settings", FormMethod.Post, new { id = "frmEditNetwork", @class = "form-horizontal" }))
{
    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        <label for="Name" class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label for="cityId" class="col-sm-2 control-label">City</label>
        <div class="col-sm-10">
            <select id="cityId" name="CityId" class="form-control">
                <option value="">Select city</option>
                @foreach (var city in Model.Cities)
                {
                    if (city.Id == Model.CityId)
                    {
                        <option value="@city.Id" selected="selected">@city.Name</option>
                    }
                    else
                    {
                        <option value="@city.Id">@city.Name</option>
                    }
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Create</button>
        </div>
    </div>
}

@section Scripts{
    <script type="text/javascript">
        $(function () {
            $('#frmEditNetwork')
                .validate({
                    rules: {
                        Name: 'required',
                        CityId: 'required'
                    },
                    messages: {
                        Name: 'Please specify advertiser name',
                        CityId: 'Please select city'
                    }
                });
        });
    </script>
}

Kigl/Views/Settings/Index.cshtml
@model Kigl.Models.SettingsModel
@{
    ViewBag.Title = "Settings";
}

<h2>Index</h2>

<div class="row">
    <div class="col-sm-6">
        <table class="table table-striped table-bordered table-country">
            <thead>
                <tr>
                    <th>Country</th>
                </tr>
            </thead>
            <tr class="country-row country-template">
                <td class="country-name"></td>
            </tr>
            @foreach (var country in Model.Countries)
            {
                <tr class="country-row" data-id="@country.Id">
                    <td class="country-name">@country.Name</td>
                </tr>
            }
        </table>
        <form class="form-inline">
            <div class="form-group">
                <input type="text" class="form-control" id="newCountryName">
            </div>
            <button type="button" class="btn btn-success btn-add-country">Add country</button>
        </form>
        <label class="error" style="display: none">Please specify country name</label>
    </div>
    <div class="col-sm-6">
        <table class="table table-striped table-bordered table-currency">
            <thead>
                <tr>
                    <th>Currency</th>
                </tr>
            </thead>
            <tr class="currency-row currency-template">
                <td class="currency-name"></td>
            </tr>
            @foreach (var currency in Model.Currencies)
            {
                <tr class="currency-row" data-id="@currency.Id">
                    <td class="currency-name">@currency.Name</td>
                </tr>
            }
        </table>
        <form class="form-inline">
            <div class="form-group">
                <input type="text" class="form-control" id="newCurrencyName">
            </div>
            <button type="button" class="btn btn-success btn-add-currency">Add currency</button>
        </form>
        <label class="error" style="display: none">Please specify currency</label>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-sm-6">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Country</th>
                    <th>City</th>
                </tr>
            </thead>
            @foreach (var city in Model.Cities)
            {
                <tr data-id="@city.Id">
                    <td>@city.Name</td>
                    <td>@city.Country.Name</td>
                </tr>
            }
        </table>
        <form class="form-inline pull-right">
            <a href="@Url.Action("EditCity", "Settings")" class="btn btn-success btn-add-network">Add city</a>
        </form>
    </div>
    <div class="col-sm-6">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Network</th>
                    <th>Country</th>
                </tr>
            </thead>
            @foreach (var network in Model.Networks)
            {
                <tr data-id="@network.Id">
                    <td>@network.Name</td>
                    <td>@network.City.Name</td>
                </tr>
            }
        </table>
        <form class="form-inline pull-right">
            <a href="@Url.Action("EditNetwork", "Settings")" class="btn btn-success btn-add-network">Add network</a>
        </form>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(function () {
            var countryTemplate = $('.country-template');
            countryTemplate.remove();

            var currencyTemplate = $('.currency-template');
            currencyTemplate.remove();

            $('.btn-add-country').click(function () {
                var newCountryName = $('#newCountryName').val();
                var error = $(this).closest('.form-inline').siblings('.error');
                if (newCountryName) {
                    $('#newCountryName').val('');
                    error.hide();
                    $.post('@Url.Action("AddCountry", "Settings")',
                        { countryName: newCountryName },
                        function (response) {
                            var country = response.data;
                            var row = countryTemplate.clone();
                            row.data('data-id', country.Id);
                            row.find('.country-name').text(country.Name);
                            $('.table-country').append(row);
                        });
                } else {
                    error.show();
                }
            });

            $('.btn-add-currency').click(function () {
                var newCurrencyName = $('#newCurrencyName').val();
                var error = $(this).closest('.form-inline').siblings('.error');
                if (newCurrencyName) {
                    $('#newCurrencyName').val('');
                    error.hide();
                    $.post('@Url.Action("AddCurrency", "Settings")',
                        { currencyName: newCurrencyName },
                        function (response) {
                            var currency = response.data;
                            var row = currencyTemplate.clone();
                            row.data('data-id', currency.Id);
                            row.find('.currency-name').text(currency.Name);
                            $('.table-currency').append(row);
                        });
                } else {
                    error.show();
                }
            });
        });
    </script>
}