Kigl/Controllers/NetworkSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ControlPanel.Common.Enums;
using ControlPanel.Domain.Contracts;
using Kigl.Domain.Contracts;
using Kigl.Filters;

namespace Kigl.Controllers
{
    [KiglAuthorize(RoleName.NetworkAdmin)]
    public class NetworkSettingsController : BaseController
    {
        private readonly INetworkSettingsService _networkSettingsService;

        public NetworkSettingsController(IUserService userService, INetworkSettingsService networkSettingsService) : base(userService)
        {
            _networkSettingsService = networkSettingsService;
        }

        public ActionResult Index()
        {
            var model = _networkSettingsService.GetNetworkSettings(CurrentUser.NetworkId.Value);
            return View(model);
        }

        [HttpPost]
        public ActionResult UpdateNetworkSetting(NetworkSetting setting, bool value)
        {
            _networkSettingsService.UpdateNetworkSetting(CurrentUser.NetworkId.Value, setting, value);
            return SuccessResult();
        }
    }
}

Kigl/Views/NetworkSettings/Index.cshtml
@using ControlPanel.Common.Enums
@using Global = Resources.Global
@model ControlPanel.Domain.Models.NetworkSettings
@{
    ViewBag.Title = "Network settings";
}

@section Styles{
    <link href="~/static/css/network-setting.css" rel="stylesheet"/>
<script src="https://use.fontawesome.com/eac71a1db9.js"></script>
}

<!-- begin network-settings -->
<div class="network-settings">
    <!-- begin network-settings__page-title -->
    <h2 class="network-settings__page-title">
        @Global.Admin_NetworkSettings
    </h2>
    <!-- end network-settings__page-title -->
    <hr>
    <!-- begin network-settings__choose-option -->
    <div class="network-settings__choose-option">
        <div class="network-settings__description">
            @Global.Admin_DisplayAdsAtThis
        </div>
        <!-- begin settings -->
        <form class="settings">
            <div class="settings__option_block">
                <input type="checkbox" id="header" class="settings__option setting-checkbox" data-setting="@NetworkSetting.ShowHeaderImage">
                <label for="header">
                    <span class="settings__title">
                        @Global.Admin_Header
                    </span>
                </label>
            </div>
            <div class="settings__option_block">
                <input type="checkbox" id="footer" class="settings__option setting-checkbox" data-setting="@NetworkSetting.ShowFooterImage">
                <label for="footer">
                    <span class="settings__title">
                        @Global.Admin_Footer
                    </span>
                </label>
            </div>
            <div class="settings__option_block">
                <input type="checkbox" id="ad" class="settings__option setting-checkbox" data-setting="@NetworkSetting.ShowAd">
                <label for="ad">
                    <span class="settings__title">
                        @Global.Admin_Ad
                    </span>
                </label>
            </div>
        </form>
        <!-- end settings -->
        <hr>

    </div>
    <!-- end network-settings__choose-option -->

</div>
<!-- end network-settings -->

@section Scripts{
    <script type="text/javascript">
        @if (Model.ShowHeaderImage)
        {<text>
        $('#header').prop('checked', true);
            </text>
        }
        @if (Model.ShowFooterImage)
        {<text>
        $('#footer').prop('checked', true);
            </text>
        }
        @if (Model.ShowAd)
        {<text>
        $('#ad').prop('checked', true);
            </text>
        }
        $(function () {
            $('.setting-checkbox').change(function () {
                $.post('@Url.Action("UpdateNetworkSetting", "NetworkSettings")',
                { setting: $(this).data('setting'), value: $(this).prop('checked') });
            });
        });
    </script>
}